### ISSUE TITLE
Update Google Analytics to 2.X

### ISSUE THREAD

**Issue by AdamGerthel** [oddhill/odddrupal#27]
[Google Analytics ](https://www.drupal.org/project/google_analytics) 1.X is no longer supported and 2.X is the recommended version.

**Comment by olofbokedal** [comment]
2.4 is currently used by Odd Drupal, and 2.0 was implemented a couple of years ago - f978694.

2.1 seems to be the one used by Odd Drupal in olssongerthel.se - https://github.com/oddhill/olssongerthel.se/blob/master/public/profiles/odddrupal/modules/contrib/google_analytics/googleanalytics.info. Perhaps there was an older override stored somewhere else in the repo?

Closing this since this most likely was a site specific issue.

**Comment by AdamGerthel** [comment]
Ah, I don't remember where I got the "1.x" from since that was never the case. 2.1 seems to be the version used in Odd Drupal that olssongerthel.se uses (i.e release 7.27).
